name: Create Automatic Issue

on:
  workflow_dispatch:  # Run manually from GitHub

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests pycryptodome

      - name: Run issue creation script
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python script.py
