name: Print Flag

on:
  workflow_dispatch:  # Run manually from GitHub

jobs:
  add_comment_ctf_challenge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests pycryptodome

      - name: Run issue creation script
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_REPOSITORY: "puckk/testctf"
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FLAG: ${{ secrets.CHALLENGE_FLAG }}
        run: python script.py
